### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/.DocumentRevisions-V100'

### ISSUE THREAD

**Issue by robstoop** [erikdewildt/django-rotating-backup#1]
When I run the backup I get the following error:

`Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/user/.virtualenvs/workinghours/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/user/.virtualenvs/workinghours/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/user/.virtualenvs/workinghours/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/user/.virtualenvs/workinghours/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/user/.virtualenvs/workinghours/lib/python3.7/site-packages/django_rotating_backup/management/commands/create_backup.py", line 13, in handle
    RotatingBackup().run()
  File "/Users/user/.virtualenvs/workinghours/lib/python3.7/site-packages/django_rotating_backup/backup.py", line 289, in run
    backup_file = self.make_media_backup(destination=destination, pattern=hour_pattern)
  File "/Users/user/.virtualenvs/workinghours/lib/python3.7/site-packages/django_rotating_backup/backup.py", line 187, in make_media_backup
    backup_file.add(file)
  File "/Users/user/.virtualenvs/workinghours/lib/python3.7/tarfile.py", line 1949, in add
    recursive, filter=filter)
  File "/Users/user/.virtualenvs/workinghours/lib/python3.7/tarfile.py", line 1947, in add
    for f in sorted(os.listdir(name)):
PermissionError: [Errno 13] Permission denied: '/.DocumentRevisions-V100'
`

**Comment by erikdewildt** [comment]
Hey Rob,

Thanks for submitting this first issue. 

The issue was caused when no `MEDIA_ROOT` folder was specified in your Django settings. 

In the latest release 0.0.5 this has been fixed. The fixes also includes some other fixes and improvements.

Regards,
Erik
